### ISSUE TITLE
Find box ctrl+left etc broken by this extension.

### ISSUE THREAD

**Issue by blalond** [woodced/Maptz.VSCode.Extensions.CamelCaseNavigation#1]
Hello! Thanks for the Extension! It's working quite well overall.

The bit that I notice is that when in VS Code's Find field (the Find Widget), the shortcuts for ctrl+left, ctrl+shift+left are broken. The cursor just sits there at the end of the string.

Maybe the fix would be in the keybindings of the extension's package.json? Or maybe in the main extension code. Something that can see when the Find Widget has the focus...

Thanks!

**Comment by woodced** [comment]
@blalond Good spot. Thanks. I've updated the context for the keybindings, and re-published the extension.

The arrow keys revert to their default behaviour in the FInd widget.
